config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # rails g deviseコマンドでUserモデルを作成すると自動でルーティングが作成される


  root to:'tweets#index'
  # 最初の画面にルーティングを設定した（よく使う画面であればどこでもいい）
  # root to: 'コントローラ名#アクション名'  (1)
  # root     'コントローラ名#アクション名'  (2)短縮系

  namespace :tweets do
    resources :searches, only: :index
  end
  # 検索機能にnamespaceを追加
  # namespace :ディレクトリ名 do ~ endと囲む形でルーティングを記述し、そのディレクトリ内のコントローラーのアクションを指定

  # showアクション追加したらエラーになった
  # 自作アクションsearchを先に読み込むように上に記載したら改善（なぜ？）
  resources :tweets do
    collection do
      get 'plus'
    end
  end


  # resources :tweets, only: :index
  # パスの指定「twwets」
  # アクションは「index」
  # 新規画面を追加したい「new」アクション
  # 投稿をテーブルに保存したい「create」アクション
  # 削除機能追加したい「destroy」アクション
  # 編集機能を追加したい「edit」アクション
  # 更新機能を追加したい「update」アクション
  # 詳細画面を追加したい「show」アクション
  # ↓下記にまとめる(7アクション全部実装の為)
  resources :tweets do
    resources :comments, only: :create
    # コメントテーブルのルーティング
    # ネストにする（イメージ：既にあるビューに追加する場合）

    # collection do
    #   get 'search'
    # end
    # 検索機能のルーティング
    # ネストにする
    # nammespaceに集約する為不要

  end

  resources :users, only: :show
  # マイページの部分
  # 個別のページ（詳細ページ）を表示したい「show」アクション
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  # コメント多→投稿1
  belongs_to :tweet  # tweetsテーブルとのアソシエーション
  belongs_to :user  # usersテーブルとのアソシエーション
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  
  # ？？mergeメソッドを作ったら下記でアソシエーションを各々作る
  belongs_to :user

  has_many :comments  
  # commentsテーブルとのアソシエーション

  
  # 検索処理を作成
  # モデムにテーブルから検索するためのsearchメソッドを定義
  def self.search(search)
    # searchメソッド
    if search
      Tweet.where('text LIKE(?)', "%#{search}%")
      # モデル名(大文字).whereメソッド
      # ('text LIKE(?)', "%#{search}%")で「searchが含まれるタイトル」で検索
    else
      Tweet.all
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable

  # mergeメソッドを作ったら下記でアソシエーションを各々作る
  has_many :tweets
  has_many :comments  
  # commentsテーブルとのアソシエーション

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# 基本コントローラーは一つでいいが、機能が増えたらコントローラーを追加することが可能

# basic認証を追加。本番環境なら実行するという条件（if: :production?）を追記してデプロイ時だけに働くようにする
# before_action :basic_auth
before_action :basic_auth, if: :production?


before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  private

  # basic認証をデプロイ時に限定するために追記
  def production?
    Rails.env.production?
  end

  # basic認証
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
      # 直接ログインID,PWはセキュリティーの観点から環境変数で設定して上記に変更する（環境変数使わなければここに入力するれば実装は可）

    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    # comment = Comment.create(comment_params)
    # Comment.create(comment_params)
    # ↑大文字、小文字
    # ↓に書き換え 理由？
    # これから作るから、find（IDの箱を見つけ出す）やIDは不要
    # これから、コメントの箱を作るというイメージ
    # redirect_to "/tweets/#{comment.tweet.id}"
    # コメントと結びつく詳細画面に遷移させる

    # 非同期通信で下記に書き換え
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html { redirect_to tweet_path(params[:tweet_id])  }
      format.json
    end

  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/tweets/searches_controller.rb
# 「検索結果の一覧」を表示するindexアクションを定義
class Tweets::SearchesController < ApplicationController
  def index
    @tweets = Tweet.search(params[:keyword])
  end
end

app/controllers/tweets_controller.rb
# 基本ここはツイートモデルのコントローラーを作成しているから、「tweetクラス」＋アクション名

class TweetsController < ApplicationController
  # 同じ記載なのでset_tweetの行でまとめる
  before_action :set_tweet, only: [:edit, :show]

  # 最初はインデックス、showアクション以外は初期画面に移動。
  # インデックスを除くのはもうそこにいてるから
  # showを除くのはログインしてなくても見れるようにするから
  before_action :move_to_index, except: [:index, :show, :search]


  # 作ったコントローラー（tweets）にアクション（index）を設定する
  def index
    # @tweets = Tweet.all
    # モデル名は大文字であることが注意！
    # ↑def アクション名
    # インスタンス変数（にしたテーブル名） =全てのレコードを渡す

    @tweets = Tweet.includes(:user).order("created_at DESC").page(params[:page]).per(8)
    # 1：includesメソッド：ツイート表示する際、アソシエーションを利用して投稿者のニックネームが表示されるように「ユーザー情報」を「先に読み込む」設定にして反映させる
    # 2：orderメソッド：順番を変更(最新が上に)
    # 3：ページネーション（8投稿毎に次ページ）
  end

  def new
    @tweet = Tweet.new
    # 新規投稿機能を実装する為に、さっき作ったコントローラー（tweets）にアクション（new）を設定する
    # 単数！
  end
  
  # 少し分かった
  def create
    # 大文字、小文字
    Tweet.create(tweet_params)
    # 「モデルのクラス名.アクション名」で、引数として保存するデータの値を用意
    # ツイートの箱を作るというイメージ
    
  end

  # 少し分かった
  def destroy
    # インスタンスがいらないのは別画面にならないから別に不要だから（多分）
    tweet = Tweet.find(params[:id])
    tweet.destroy
    # findはどれにするか対象を選択する（IDの箱を見つけ出す）時に使うイメージ
  end

  # 未だわからん
  def edit
    # @tweet = Tweet.find(params[:id])
  end

  # 未だわからん
  def update
    # デストロイ同様、インスタンスがいらないのは別画面にならないから別に不要だから（多分）
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
  end

  def show
    # ↓ここはeditと同じなのは、なんで？
    # 同じだからbefore actionでまとめる
    # @tweet = Tweet.find(params[:id])

    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
    # コメント機能追加実装
  end

  def search
    @tweets = Tweet.search(params[:keyword])
  end
    # 変数（あだ名付けれる空箱）＝モデム名.アクション名
  
  def plus
  end
  
  
  


  # 未だわからん
  private
  # プライベートメソッドはアクセスを制約する為のメソッド

  def tweet_params

    # params.permit(:name, :image, :text) これは間違い
    # requireがないとparamsの中の指定の値の存在をチェック出来ない（お墨付きをえていないからエラーになる）

    # params.require(:tweet).permit(:name, :image, :text)
    # ダブルチェックしている
    # 1：requireがparamsの中に指定の値があるかチェックする
    # 2：permitが:name以下の項目が用意されているかチェックする
    
    # params.require(:tweet).permit(:name, :image, :text).merge(user_id: current_user.id)
    # mergeメソッドで2つのハッシュ（ユーザーID）を統合

    params.require(:tweet).permit(:image, :text).merge(user_id: current_user.id)
    # :nameカラムを削除
    # それにより、「ツイートの保存時」にnameカラムに情報を保存しないよう変更

  end

  # before actionを定義したらこれが最後にいる今回は2つしか同じとこないから、メリットない
  def set_tweet
    @tweet = Tweet.find(params[:id]) 
  end

  # ログインしていない場合、indexアクションのindex.html.erbのページにリダイレクトする
  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # マイページに表示させたいものはここで追加出来る(表示できる)
  def show

    # @nickname = current_user.nickname
    # ↑@nicknameは、ログインユーザーのニックネームを取得する

    # @tweets = current_user.tweets
    # ↑@tweets:ログインユーザーの投稿を取得する
    # ↑「 current_user」のままだと、どの投稿者の投稿を選択しても、現在ログインしているユーザーのマイページしか表示されない

    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets.page(params[:page]).per(8).order("created_at DESC")
    # マイページ側にもページネーション追加

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets/searches_helper.rb
module Tweets::SearchesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<%# トップ画面 %>
<!DOCTYPE html>
<html>
  <head>
    <title>TOKYO2020 puls1</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <header class="header">
      <div class="header__bar row">
          <h1 class="grid-6">
            <div class="title_2020">
            TOKYO2020
            </div>
            <a href="/">　Official licensed product 投稿サイト</a>
          </h1>
          <%# ↑"/"で最初の投稿ページへ戻れるようになる %>

        <%# ログインしていたら %>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.nickname %>
              <ul class="user__info">
                <li>
                  <%= link_to "マイページ", "/users/#{current_user.id}" %>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </span>
            <%= link_to  "投稿する", "/tweets/new", class: "post" %>
            <%# newの投稿ページに移動出来る %>
            
            <%# <%= link_to  "➡️ Plus1", "/tweets/plus", class: "post" %> 
            <%# 新たに作った「plusのビュー」に移動出来る %>
          </div>
          
        <%# ログインしていなかったら %>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: 'post' %>
            <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
          </div>
        <% end %>
        </div>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>
        <a href="/">TOPへ戻る</a>
      </p>
      <p>
        <a href="/">TOKYO2020 ➡️  plus1.</a>
      </p>
        
    </footer>
  </body>
</html>

app/views/tweets/_tweet.html.erb
<div class="content_post" style="background-image: url(<%= tweet.image %>);">
  <div class="more">
    <%# <span><%= image_tag 'arrow_top.png' %>
    <%# </span> %> 
    <ul class="more_list">
      <li>
        <%= link_to 'コメント', "/tweets/#{tweet.id}", method: :get %>
      </li>
      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <li>
          <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
        </li>
      <% end %>
    </ul>
  </div>
  <%= simple_format(tweet.text) %>
  <%# sinple_format使うことによって「改行」になる %>

  <span class="name">
    <a href="/users/<%= tweet.user.id %>">
    <%# 「ツイートしたユーザーID」の「ユーザーのページ（専用のページ）」に移動する %>

      <span>ニックネーム</span><%= tweet.user.nickname %>
      <%# リンク先の表示を何にするかは自由（例 ニックネーム、IDとか) %>
    </a>
  </span>
</div>

app/views/tweets/create.html.erb
<%# 投稿完了すると遷移 %>
<div class="contents row">
  <div class="success">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="btn" href="/tweets">投稿一覧へ戻る</a>
    <%# href="/tweets"で最初の画面に戻る %>
  </div>
</div>

app/views/tweets/destroy.html.erb
<%# 削除ボタン押すと遷移 %>
<div class="contents row">
  <div class="success">
      削除が完了しました。
    </h3>
    <a class="btn" href="/tweets">投稿一覧へ戻る</a>
    <%# ここで↑ボタン押すと「ルート（/）」へ移動する %>
    <%# これだけではだめ。ルーティングで「ルート（/）」はどこかを指定しておく %>
    <%# 「ルート（/）」→から「/tweets」に書き換えることによって、投稿の最初の画面に移動 %>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="contents row">
  <div class="container">
    <%= form_with(model: @tweet, local: true) do |form| %>
      <h3>
        編集する
      </h3>
      <%# <%= form.text_field :name, placeholder: "Nickname" %>
      <%= form.text_field :image, placeholder: "Image Url" %>
      <%= form.text_area :text, placeholder: "text" , rows: "10" %>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/tweets/index-en.html.erb
<%# 言語切り替え項目 %>
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>5-02_location</title>
</head>
<body>
  <h1>English Page</h1>
  <h2>最初に選択されている項目を切り替える</h2>
  <form id="form">
    <select name="select">
      <option value="index.html">日本語</option>
      <option value="index-en.html">English</option>
      <option value="index-zh.html">中文</option>
    </select>
  </form>
  <h2>English Page</h2>
  <script src="script.js"></script>
</body>
</html>

app/views/tweets/index-zh.html.erb
<%# 言語切り替え項目 %>
<!doctype html>
<html lang="zh">
<head>
  <meta charset="UTF-8">
  <title>5-02_location</title>
</head>
<body>
  <h1>Chinese Page</h1>
  <h2>最初に選択されている項目を切り替える</h2>
  <form id="form">
    <select name="select">
      <option value="index.html">日本語</option>
      <option value="index-en.html">English</option>
      <option value="index-zh.html">中文</option>
    </select>
  </form>
  <h2>中文的页</h2>
  <script src="script.js"></script>
</body>
</html>

app/views/tweets/index.html.erb
<%# 検索画面 %>
<%= form_with(url: tweets_searches_path, local: true, method: :get, class: "search-form") do |form| %>
<%# form_withのモデル（DB）使わないパターン %>
<%# メソッドはHTTPメソッド %>

  <%= form.text_field :keyword, placeholder: "投稿したライセンス商品を検索する", class: "search-input" %>
  <%# 検索窓を作成 %>

  <%= form.submit "検索", class: "search-btn" %>
  <%# 検索ボタン %>

<% end %>
<%# ↑検索機能を実装 %>

<%# トップページ %>
<div class="contents all">
  <div class="contents row">

    <% @tweets.each do |tweet| %>
    <%# each文で全てのツイートを表示させる %>

      <%= render partial: "tweet", locals: { tweet: tweet } %>
      <%# each〜endの間を全部、部分テンプレートで置き換え。可読性アップ。 %>
    <% end %>
    <%= paginate(@tweets) %>
    <%# paginateメソッド：ページネーションのリンクを表示したいときに使用するメソッド %>
  </div>
</div>

app/views/tweets/new.html.erb
<%# 新規投稿画面 %>
<div class="contents row">
  <div class="container">
    <%= form_with(model: @tweet, local: true) do |form| %>
      <h3>
        投稿する
      </h3>
      <%# <%= form.text_field :name, placeholder: "Nickname" %> 
      <%= form.text_field :image, placeholder: "Image URL（必須）" %>
      <%= form.text_area :text, placeholder: "コメント（必須）" , rows: "10" %>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/tweets/plus.html.erb
  <div class="plus-header">
    <h2>最初に選択されている項目を切り替える</h2>
    <form id="form">
      <select name="select">
      <option value="index.html">日本語</option>
      <option value="index-en.html">English</option>
      <option value="index-zh.html">中文</option>
      </select>
    </form>
    <h2>日本語の東京2020の公式ページへ</h2>
    <script src="script.js"></script>
    
  </div>
  <div class="k_main__mainVisual">
  <div class="k_main__mainVisual__content"></div>
  <div class="k_main__mainVisual__subtitle">
  オリンピックを観戦してさらなる感動を！
  </div>

  <div class='select-sports'>
    <p>好きなスポーツ</p>
      <form>
      <select name="sel2">
      <option value="#"></option>
      <option value="選択してください">選択してください</option>
      <option value="https://tokyo2020.org/ja/sports/athletics/">陸上</option>
      <option value="https://tokyo2020.org/ja/sports/swimming/">水泳</option>
      <option value="https://tokyo2020.org/ja/sports/baseball-softball/">野球・ソフトボール</option>
      <option value="https://tokyo2020.org/ja/sports/football/">サッカー</option>
      <option value="https://tokyo2020.org/ja/sports/handball/">ハンドボール</option>
      <option value="https://tokyo2020.org/ja/sports/basketball/">バスケットボール</option>
      <option value="https://tokyo2020.org/ja/sports/volleyball/">バレーボール</option>
      <option value="https://tokyo2020.org/ja/sports/hockey/">ホッケー</option>
      <option value="https://tokyo2020.org/ja/sports/rugby/">ラグビー</option>
      <option value="https://tokyo2020.org/ja/sports/canoe-slalom/">カヌー</option>
      <option value="https://tokyo2020.org/ja/sports/sailing/">セーリング</option>
      <option value="https://tokyo2020.org/ja/sports/table-tennis/">卓球</option>
      <option value="https://tokyo2020.org/ja/sports/tennis/">テニス</option>
      <option value="https://tokyo2020.org/ja/sports/badminton/ ">バドミントン </option>
      <option value="https://tokyo2020.org/ja/sports/judo/">柔道</option>
      <option value="https://tokyo2020.org/ja/sports/karate/">空手</option>
      <option value="https://tokyo2020.org/ja/sports/fencing/">フェンシング</option>
      <option value="https://tokyo2020.org/ja/sports/archery/">アーチェリー</option>
      <option value="https://tokyo2020.org/ja/sports/artistic-gymnastics/">体操競技</option>
      <option value="https://tokyo2020.org/ja/sports/weightlifting/">ウェイトリフティング</option>
      <option value="https://tokyo2020.org/ja/sports/cycling-bmx-racing/">バイク（BMX）</option>
      <option value="https://tokyo2020.org/ja/sports/modern-pentathlon/">近代五種</option>
      <option value="https://tokyo2020.org/ja/sports/golf/">ゴルフ</option>
      <option value="https://tokyo2020.org/ja/sports/triathlon/">トライアスロン</option>
      </select>
      <input type=button onClick="top.location.href=sel2.value" value="Jump!">
      </form>
  </div>
  
  <div class="venue-place">
  会場
  </div>  
  <div class="image-link">
    <img src="/images/2020.png" usemap="#ImageMap" alt="自転車競技1（BMXレーシング）" width="1200px" height="400px"/>
  </div>

  <div class="image-discipline">
    <img src="/images/2020-05-25 23.40.11.png" usemap="#ImageMap" href="https://tokyo2020.org/ja/sports/tennis/" width="1200px" height="400px" alt="競泳"/>
    <img src="/images/2020_tennis.png" usemap="#ImageMap" href="https://tokyo2020.org/ja/sports/tennis/" width="1200px" height="400px" alt="テニス"/>
    <map name="ImageMap">
      <area shape="poly" coords="12,6,1011,472"  alt="テニスのリンク"/>
    </map>
    <img src="/images/2020-05-25 23.39.33.png" usemap="#ImageMap" href="https://tokyo2020.org/ja/sports/tennis/"  width="1200px" height="400px" alt="野球"/>
    <img src="/images/2020-05-25 23.39.44.png" usemap="#ImageMap" href="https://tokyo2020.org/ja/sports/tennis/" width="1200px" height="400px" alt="バスケットボール"/>
  </div>

app/views/tweets/search.erb
<%# 検索結果画面のビュー %>
<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
</div>

app/views/tweets/search.html.erb
<h1>ここに別ページ作りたい</h1>

<div class="k_main__mainVisual">
<div class="k_main__mainVisual__content"></div>
<div class="k_main__mainVisual__subtitle">
オリンピックを観戦してさらなる感動を！
</div>
<p>
</p><div class="k_main__mainVisual__subtitle__text">
<%# だれでもカンタンに出品・購入できる %>
<br>
<%# フリマアプリです %>
<div class="k_main__mainVisual__subtitle__btn">
<img class="k_main__mainVisual__subtitle__btn__a" src="/assets/app-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg">
<img class="k_main__mainVisual__subtitle__btn__b" src="/assets/google-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg">
</div>
</div>
<p></p>
</div>

app/views/tweets/searches/index.html.erb
<%# 検索結果の一覧画面 %>
<%= form_with(url: tweets_searches_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweets/tweet", locals: { tweet: tweet } %>
  <% end %>
</div>

app/views/tweets/show.html.erb
<%# 選択したツイートの詳細ページ %>
<%# マイページではないので基本1つだけ表示 %>
<%# アカウントごとの投稿ページは、マイページとして後ほど作成 %>
<div class ="contents row">
  <div class="content_post" style="background-image: url(<%= @tweet.image %>);">

    <%# ログイン時、且つ、現在のユーザーIDとツイートのIDが同じならOK %>
    <% if user_signed_in? && current_user.id == @tweet.user_id %>

      <div class="more">
        <span><%= image_tag 'arrow_top46.png' %></span>
        
        <ul class="more_list">
          <li>
            <%= link_to '編集', "/tweets/#{@tweet.id}/edit", method: :get %>
          </li>
          <li>
            <%= link_to '削除', "/tweets/#{@tweet.id}", method: :delete %>
          </li>
        </ul>
      </div>
    <% end %>
    
    <%= simple_format(@tweet.text) %>
    <span class="name">
      <%# <a href="/users/<%= @tweet.user.id %>
      <span>ニックネーム</span><%= @tweet.user.nickname %>
    </span>
  </div>
  <%# ↓コメント機能のビュー %>
  <div class="container">
    <% if current_user %>
      <%# ↓非同期通信で下記３行修正 %>
      <%= form_with(model: [@tweet, @comment], local: true, id: "new_comment") do |form| %> 
        <%= form.text_area :text, placeholder: "コメントする" , rows: "2", class: "textbox" %>
        <%= form.submit "SEND", class: "form__submit" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメント投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
      <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      更新が完了しました。
    </h3>
    <a class="btn" href="/tweets">投稿一覧へ戻る</a>
    <%# ↑"/tweets"で最初に投稿画面に移動する %>
  </div>
</div>

app/views/users/show.html.erb
<%# マイページ %>
<div class="contents row">
  <p class="show_nickname"><%= @nickname %>さんの投稿一覧</p>

  <% @tweets.each do |tweet| %>
    <%= render partial: "tweets/tweet", locals: { tweet: tweet } %>
    <%# マイページも部分テンプレート使用して、マイページ内で編集等出来るように設定 %>

    <%# <span class="name"><%= tweet.name</span>  %>
    <%# ↑削除。ツイートテーブルで「nameカラム」不要になったから %>
  <% end %>
  <%= paginate(@tweets) %>
  <%# マイページ側にもページネーション追加 %>
  
  <ul class="example3">
  <li class="pre">前へ</li>
  <li class="this">1</li>
  <li><a href="page-2.html">2</a></li>
  <li><a href="page-3.html">3</a></li>
  <li><a href="page-2.html">次へ</a></li>
  </ul>

</div>